import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" id="html" className={`font-mono h-full`}>
      <body className="h-full dark:bg-darkBlack bg-lightGrey transition-all">
        {children}
      </body>
    </html>
  );
}
